package route

#Properties: {
	// The API identifier.
	ApiId: string
	// Specifies whether an API key is required for the route. Supported only for WebSocket APIs.
	ApiKeyRequired?: bool
	// The authorization scopes supported by this route.
	AuthorizationScopes?: [...string]
	// The authorization type for the route. For WebSocket APIs, valid values are ``NONE`` for open access, ``AWS_IAM`` for using AWS IAM permissions, and ``CUSTOM`` for using a Lambda authorizer. For HTTP APIs, valid values are ``NONE`` for open access, ``JWT`` for using JSON Web Tokens, ``AWS_IAM`` for using AWS IAM permissions, and ``CUSTOM`` for using a Lambda authorizer.
	AuthorizationType?: string
	// The identifier of the ``Authorizer`` resource to be associated with this route. The authorizer identifier is generated by API Gateway when you created the authorizer.
	AuthorizerId?: string
	// The model selection expression for the route. Supported only for WebSocket APIs.
	ModelSelectionExpression?: string
	// The operation name for the route.
	OperationName?: string
	// The request models for the route. Supported only for WebSocket APIs.
	RequestModels?: {...}
	// The request parameters for the route. Supported only for WebSocket APIs.
	RequestParameters?: {...}
	// The route key for the route. For HTTP APIs, the route key can be either ``$default``, or a combination of an HTTP method and resource path, for example, ``GET /pets``.
	RouteKey: string
	// The route response selection expression for the route. Supported only for WebSocket APIs.
	RouteResponseSelectionExpression?: string
	// The target for the route.
	Target?: string
}

#ParameterConstraints: {
	Required: bool
}
