package vpcendpoint

#Properties: {
	// Describes the DNS options for an endpoint.
	DnsOptions?: #DnsOptionsSpecification
	// The supported IP address types.
	IpAddressType?: "ipv4" | "ipv6" | "dualstack" | "not-specified"
	// An endpoint policy, which controls access to the service from the VPC. The default endpoint policy allows full access to the service. Endpoint policies are supported only for gateway and interface endpoints.
	// For CloudFormation templates in YAML, you can provide the policy in JSON or YAML format. For example, if you have a JSON policy, you can convert it to YAML before including it in the YAML template, and CFNlong converts the policy to JSON format before calling the API actions for privatelink. Alternatively, you can include the JSON directly in the YAML, as shown in the following ``Properties`` section:
	// ``Properties: VpcEndpointType: 'Interface' ServiceName: !Sub 'com.amazonaws.${AWS::Region}.logs' PolicyDocument: '{ "Version":"2012-10-17", "Statement": [{ "Effect":"Allow", "Principal":"*", "Action":["logs:Describe*","logs:Get*","logs:List*","logs:FilterLogEvents"], "Resource":"*" }] }'``
	PolicyDocument?: string
	// Indicate whether to associate a private hosted zone with the specified VPC. The private hosted zone contains a record set for the default public DNS name for the service for the Region (for example, ``kinesis.us-east-1.amazonaws.com``), which resolves to the private IP addresses of the endpoint network interfaces in the VPC. This enables you to make requests to the default public DNS name for the service instead of the public DNS names that are automatically generated by the VPC endpoint service.
	// To use a private hosted zone, you must set the following VPC attributes to ``true``: ``enableDnsHostnames`` and ``enableDnsSupport``.
	// This property is supported only for interface endpoints.
	// Default: ``false``
	PrivateDnsEnabled?: bool
	// The Amazon Resource Name (ARN) of the resource configuration.
	ResourceConfigurationArn?: string
	// The IDs of the route tables. Routing is supported only for gateway endpoints.
	RouteTableIds?: [...string]
	// The IDs of the security groups to associate with the endpoint network interfaces. If this parameter is not specified, we use the default security group for the VPC. Security groups are supported only for interface endpoints.
	SecurityGroupIds?: [...string | string | string]
	// The name of the endpoint service.
	ServiceName?: string
	// The Amazon Resource Name (ARN) of the service network.
	ServiceNetworkArn?: string
	// Describes a Region.
	ServiceRegion?: string
	// The IDs of the subnets in which to create endpoint network interfaces. You must specify this property for an interface endpoint or a Gateway Load Balancer endpoint. You can't specify this property for a gateway endpoint. For a Gateway Load Balancer endpoint, you can specify only one subnet.
	SubnetIds?: [...string]
	// The tags to associate with the endpoint.
	Tags?: [...#Tag]
	// The type of endpoint.
	// Default: Gateway
	VpcEndpointType?: "Interface" | "Gateway" | "GatewayLoadBalancer" | "ServiceNetwork" | "Resource"
	// The ID of the VPC.
	VpcId: string
}

#DnsOptionsSpecification: {
	// The DNS records created for the endpoint.
	DnsRecordIpType?: "ipv4" | "ipv6" | "dualstack" | "service-defined" | "not-specified"
	// Indicates whether to enable private DNS only for inbound endpoints. This option is available only for services that support both gateway and interface endpoints. It routes traffic that originates from the VPC to the gateway endpoint and traffic that originates from on-premises to the interface endpoint.
	PrivateDnsOnlyForInboundResolverEndpoint?: "OnlyInboundResolver" | "AllResolvers" | "NotSpecified"
	// The preference for which private domains have a private hosted zone created for and associated with the specified VPC. Only supported when private DNS is enabled and when the VPC endpoint type is ServiceNetwork or Resource.
	PrivateDnsPreference?: "VERIFIED_DOMAINS_ONLY" | "ALL_DOMAINS" | "VERIFIED_DOMAINS_AND_SPECIFIED_DOMAINS" | "SPECIFIED_DOMAINS_ONLY"
	// Indicates which of the private domains to create private hosted zones for and associate with the specified VPC. Only supported when private DNS is enabled and the private DNS preference is ``VERIFIED_DOMAINS_AND_SPECIFIED_DOMAINS`` or ``SPECIFIED_DOMAINS_ONLY``.
	PrivateDnsSpecifiedDomains?: [...string & strings.MinRunes(1) & strings.MaxRunes(255)]
}

#Tag: {
	// The key of the tag.
	// Constraints: Tag keys are case-sensitive and accept a maximum of 127 Unicode characters. May not begin with ``aws:``.
	Key: string
	// The value of the tag.
	// Constraints: Tag values are case-sensitive and accept a maximum of 256 Unicode characters.
	Value: string
}
