package datalake

#Properties: {
	EncryptionConfiguration?: #EncryptionConfiguration
	LifecycleConfiguration?: #LifecycleConfiguration
	// The Amazon Resource Name (ARN) used to index AWS Glue table partitions that are generated by the ingestion and normalization of AWS log sources and custom sources.
	MetaStoreManagerRoleArn?: string & =~"^arn:.*$"
	ReplicationConfiguration?: #ReplicationConfiguration
	Tags?: [...#Tag]
}

#Days: int & >=1

#EncryptionConfiguration: {
	// The id of KMS encryption key used by Amazon Security Lake to encrypt the Security Lake object.
	KmsKeyId?: string
}

#Expiration: {
	Days?: #Days
}

#LifecycleConfiguration: {
	Expiration?: #Expiration
	// Provides data storage transition details of Amazon Security Lake object.
	Transitions?: [...#Transitions]
}

#Regions: [...string & =~"^(us(-gov)?|af|ap|ca|eu|me|sa)-(central|north|(north(?:east|west))|south|south(?:east|west)|east|west)-\\d+$"]

#ReplicationConfiguration: {
	Regions?: #Regions
	// Replication settings for the Amazon S3 buckets. This parameter uses the AWS Identity and Access Management (IAM) role you created that is managed by Security Lake, to ensure the replication setting is correct.
	RoleArn?: string & =~"^arn:.*$"
}

#Tag: {
	// The key name of the tag. You can specify a value that is 1 to 128 Unicode characters in length and cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, `_`, `.`, `/`, `=`, `+`, and `-`.
	Key: string
	// The value for the tag. You can specify a value that is 0 to 256 characters in length.
	Value: string
}

#Transitions: {
	// Number of days before data transitions to a different S3 Storage Class in the Amazon Security Lake object.
	Days?: int & >=1
	// The range of storage classes that you can choose from based on the data access, resiliency, and cost requirements of your workloads.
	StorageClass?: string
}
