package action

import "strings"

#Properties: {
	// The name of the action. Must be unique to your account in an AWS Region.
	ActionName: string & =~"^[a-zA-Z0-9](-*[a-zA-Z0-9]){0,119}$" & strings.MinRunes(1) & strings.MaxRunes(120)
	// The action type.
	ActionType: string & strings.MaxRunes(256)
	// The description of the action.
	Description?: string & strings.MaxRunes(3072)
	// Metadata properties of the tracking entity, trial, or trial component.
	MetadataProperties?: #MetadataProperties
	// A list of properties to add to the action.
	Properties?: {...}
	// The source type, ID, and URI.
	Source: #ActionSource
	// The status of the action.
	Status?: "Unknown" | "InProgress" | "Completed" | "Failed" | "Stopping" | "Stopped"
	// A list of tags to apply to the action.
	Tags?: [...#Tag]
}

#ActionSource: {
	// The ID of the source.
	SourceId?: string & strings.MaxRunes(256)
	// The type of the source.
	SourceType?: string & strings.MaxRunes(256)
	// The URI of the source.
	SourceUri: string & strings.MinRunes(1) & strings.MaxRunes(2048)
}

#MetadataProperties: {
	// The commit ID.
	CommitId?: string & strings.MaxRunes(1024)
	// The entity this entity was generated by.
	GeneratedBy?: string & strings.MaxRunes(1024)
	// The project ID.
	ProjectId?: string & strings.MaxRunes(1024)
	// The repository.
	Repository?: string & strings.MaxRunes(1024)
}

#Tag: {
	// The tag key.
	Key: string & =~"^([\\p{L}\\p{Z}\\p{N}_.:/=+\\-@]*)$" & strings.MinRunes(1) & strings.MaxRunes(128)
	// The tag value.
	Value: string & =~"^([\\p{L}\\p{Z}\\p{N}_.:/=+\\-@]*)$" & strings.MaxRunes(256)
}
