package modelpackage

import "strings"

#Properties: {
	AdditionalInferenceSpecifications?: #AdditionalInferenceSpecifications
	AdditionalInferenceSpecificationsToAdd?: #AdditionalInferenceSpecifications
	ApprovalDescription?: #ApprovalDescription
	CertifyForMarketplace?: #CertifyForMarketplace
	ClientToken?: #ClientToken
	CustomerMetadataProperties?: #CustomerMetadataProperties
	Domain?: #Domain
	DriftCheckBaselines?: #DriftCheckBaselines
	InferenceSpecification?: #InferenceSpecification
	MetadataProperties?: #MetadataProperties
	ModelApprovalStatus?: #ModelApprovalStatus
	ModelCard?: #ModelCard
	ModelMetrics?: #ModelMetrics
	ModelPackageDescription?: #ModelPackageDescription
	ModelPackageGroupName?: #ModelPackageGroupName
	ModelPackageName?: #ModelPackageName
	ModelPackageStatusDetails?: #ModelPackageStatusDetails
	ModelPackageVersion?: #ModelPackageVersion
	SamplePayloadUrl?: #SamplePayloadUrl
	SecurityConfig?: #SecurityConfig
	SkipModelValidation?: #SkipModelValidation
	SourceAlgorithmSpecification?: #SourceAlgorithmSpecification
	SourceUri?: #SourceUri
	// An array of key-value pairs to apply to this resource.
	Tags?: [...#Tag]
	Task?: #Task
	ValidationSpecification?: #ValidationSpecification
}

#AdditionalInferenceSpecificationDefinition: {
	// The Amazon ECR registry path of the Docker image that contains the inference code.
	Containers: [...#ModelPackageContainerDefinition]
	// A description of the additional Inference specification.
	Description?: string & =~".*" & strings.MaxRunes(1024)
	// A unique name to identify the additional inference specification. The name must be unique within the list of your additional inference specifications for a particular model package.
	Name: string & =~"^[a-zA-Z0-9](-*[a-zA-Z0-9]){0,62}$" & strings.MinRunes(1) & strings.MaxRunes(63)
	// The supported MIME types for the input data.
	SupportedContentTypes?: [...#ContentType]
	// A list of the instance types that are used to generate inferences in real-time
	SupportedRealtimeInferenceInstanceTypes?: [...#InferenceInstanceType]
	// The supported MIME types for the output data.
	SupportedResponseMIMETypes?: [...#ResponseMIMEType]
	// A list of the instance types on which a transformation job can be run or on which an endpoint can be deployed.
	SupportedTransformInstanceTypes?: [...#TransformInstanceType]
}

#Bias: {
	PostTrainingReport?: #MetricsSource
	PreTrainingReport?: #MetricsSource
	Report?: #MetricsSource
}

#DataSource: {
	S3DataSource: #S3DataSource
}

#DriftCheckBaselines: {
	Bias?: #DriftCheckBias
	Explainability?: #DriftCheckExplainability
	ModelDataQuality?: #DriftCheckModelDataQuality
	ModelQuality?: #DriftCheckModelQuality
}

#DriftCheckBias: {
	ConfigFile?: #FileSource
	PostTrainingConstraints?: #MetricsSource
	PreTrainingConstraints?: #MetricsSource
}

#DriftCheckExplainability: {
	ConfigFile?: #FileSource
	Constraints?: #MetricsSource
}

#DriftCheckModelDataQuality: {
	Constraints?: #MetricsSource
	Statistics?: #MetricsSource
}

#DriftCheckModelQuality: {
	Constraints?: #MetricsSource
	Statistics?: #MetricsSource
}

#Explainability: {
	Report?: #MetricsSource
}

#FileSource: {
	// The digest of the file source.
	ContentDigest?: string & =~"^[Ss][Hh][Aa]256:[0-9a-fA-F]{64}$" & strings.MaxRunes(72)
	// The type of content stored in the file source.
	ContentType?: string & =~".*" & strings.MaxRunes(256)
	// The Amazon S3 URI for the file source.
	S3Uri: string & =~"^(https|s3)://([^/]+)/?(.*)$" & strings.MaxRunes(1024)
}

#InferenceSpecification: {
	// The Amazon ECR registry path of the Docker image that contains the inference code.
	Containers: [...#ModelPackageContainerDefinition]
	// The supported MIME types for the input data.
	SupportedContentTypes: [...#ContentType]
	// A list of the instance types that are used to generate inferences in real-time
	SupportedRealtimeInferenceInstanceTypes?: [...#InferenceInstanceType]
	// The supported MIME types for the output data.
	SupportedResponseMIMETypes: [...#ResponseMIMEType]
	// A list of the instance types on which a transformation job can be run or on which an endpoint can be deployed.
	SupportedTransformInstanceTypes?: [...#TransformInstanceType]
}

#MetadataProperties: {
	// The commit ID.
	CommitId?: string & =~".*" & strings.MaxRunes(1024)
	// The entity this entity was generated by.
	GeneratedBy?: string & =~".*" & strings.MaxRunes(1024)
	// The project ID metadata.
	ProjectId?: string & =~".*" & strings.MaxRunes(1024)
	// The repository metadata.
	Repository?: string & =~".*" & strings.MaxRunes(1024)
}

#MetricsSource: {
	// The digest of the metric source.
	ContentDigest?: string & =~"^[Ss][Hh][Aa]256:[0-9a-fA-F]{64}$" & strings.MaxRunes(72)
	// The type of content stored in the metric source.
	ContentType: string & =~".*" & strings.MaxRunes(256)
	// The Amazon S3 URI for the metric source.
	S3Uri: string & =~"^(https|s3)://([^/]+)/?(.*)$" & strings.MaxRunes(1024)
}

#ModelAccessConfig: {
	// Specifies agreement to the model end-user license agreement (EULA).
	AcceptEula: bool
}

#ModelCard: {
	// The content of the model card.
	ModelCardContent: string & =~".*" & strings.MinRunes(0) & strings.MaxRunes(100000)
	// The approval status of the model card within your organization.
	ModelCardStatus: "Draft" | "PendingReview" | "Approved" | "Archived"
}

#ModelDataQuality: {
	Constraints?: #MetricsSource
	Statistics?: #MetricsSource
}

#ModelDataSource: {
	S3DataSource?: #S3ModelDataSource
}

#ModelMetrics: {
	Bias?: #Bias
	Explainability?: #Explainability
	ModelDataQuality?: #ModelDataQuality
	ModelQuality?: #ModelQuality
}

#ModelPackageContainerDefinition: {
	// The DNS host name for the Docker container.
	ContainerHostname?: string & =~"^[a-zA-Z0-9](-*[a-zA-Z0-9]){0,62}" & strings.MaxRunes(63)
	Environment?: #Environment
	// The machine learning framework of the model package container image.
	Framework?: string
	// The framework version of the Model Package Container Image.
	FrameworkVersion?: string & =~"[0-9]\\.[A-Za-z0-9.]+" & strings.MinRunes(3) & strings.MaxRunes(10)
	// The Amazon EC2 Container Registry (Amazon ECR) path where inference code is stored.
	Image: string & =~"[\\S]{1,255}" & strings.MinRunes(1) & strings.MaxRunes(255)
	// An MD5 hash of the training algorithm that identifies the Docker image used for training.
	ImageDigest?: string & =~"^[Ss][Hh][Aa]256:[0-9a-fA-F]{64}$" & strings.MaxRunes(72)
	ModelDataSource?: #ModelDataSource
	// A structure with Model Input details.
	ModelDataUrl?: string & =~"^(https|s3)://([^/]+)/?(.*)$" & strings.MaxRunes(1024)
	ModelInput?: {
		DataInputConfig: string & =~"[\\S\\s]+" & strings.MinRunes(1) & strings.MaxRunes(1024)
	}
	// The name of a pre-trained machine learning benchmarked by Amazon SageMaker Inference Recommender model that matches your model.
	NearestModelName?: string
}

#ModelPackageStatusDetails: {
	ValidationStatuses?: [...#ModelPackageStatusItem]
}

#ModelPackageStatusItem: {
	// If the overall status is Failed, the reason for the failure.
	FailureReason?: string
	// The name of the model package for which the overall status is being reported.
	Name: string & =~"^[a-zA-Z0-9](-*[a-zA-Z0-9]){0,62}$" & strings.MinRunes(1) & strings.MaxRunes(63)
	// The current status.
	Status: "NotStarted" | "Failed" | "InProgress" | "Completed"
}

#ModelQuality: {
	Constraints?: #MetricsSource
	Statistics?: #MetricsSource
}

#S3DataSource: {
	// The S3 Data Source Type
	S3DataType: "ManifestFile" | "S3Prefix" | "AugmentedManifestFile"
	// Depending on the value specified for the S3DataType, identifies either a key name prefix or a manifest.
	S3Uri: string & =~"^(https|s3)://([^/]+)/?(.*)$" & strings.MaxRunes(1024)
}

#S3ModelDataSource: {
	// Specifies how the ML model data is prepared.
	CompressionType: "None" | "Gzip"
	ModelAccessConfig?: #ModelAccessConfig
	// Specifies the type of ML model data to deploy.
	S3DataType: "S3Prefix" | "S3Object"
	// Specifies the S3 path of ML model data to deploy.
	S3Uri: string & =~"^(https|s3)://([^/]+)/?(.*)$" & strings.MaxRunes(1024)
}

#SecurityConfig: {
	// The AWS KMS Key ID (KMSKeyId) used for encryption of model package information.
	KmsKeyId: string & =~"^[a-zA-Z0-9:/_-]*$" & strings.MaxRunes(2048)
}

#SourceAlgorithm: {
	// The name of an algorithm that was used to create the model package. The algorithm must be either an algorithm resource in your Amazon SageMaker account or an algorithm in AWS Marketplace that you are subscribed to.
	AlgorithmName: string & =~"(arn:aws[a-z\\-]*:sagemaker:[a-z0-9\\-]*:[0-9]{12}:[a-z\\-]*\\/)?([a-zA-Z0-9]([a-zA-Z0-9-]){0,62})(?<!-)$" & strings.MinRunes(1) & strings.MaxRunes(170)
	// The Amazon S3 path where the model artifacts, which result from model training, are stored. This path must point to a single gzip compressed tar archive (.tar.gz suffix).
	ModelDataUrl?: string & =~"^(https|s3)://([^/]+)/?(.*)$" & strings.MaxRunes(1024)
}

#SourceAlgorithmSpecification: {
	// A list of algorithms that were used to create a model package.
	SourceAlgorithms: [...#SourceAlgorithm]
}

#Tag: {
	// The key name of the tag. You can specify a value that is 1 to 127 Unicode characters in length and cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -.
	Key: string & =~"^([\\p{L}\\p{Z}\\p{N}_.:/=+\\-@]*)$" & strings.MinRunes(1) & strings.MaxRunes(128)
	// The value for the tag. You can specify a value that is 1 to 255 Unicode characters in length and cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -.
	Value: string & =~"^([\\p{L}\\p{Z}\\p{N}_.:/=+\\-@]*)$" & strings.MaxRunes(256)
}

#TransformInput: {
	// If your transform data is compressed, specify the compression type. Amazon SageMaker automatically decompresses the data for the transform job accordingly. The default value is None.
	CompressionType?: "None" | "Gzip"
	// The multipurpose internet mail extension (MIME) type of the data. Amazon SageMaker uses the MIME type with each http call to transfer data to the transform job.
	ContentType?: string & =~".*" & strings.MaxRunes(256)
	DataSource: #DataSource
	// The method to use to split the transform job's data files into smaller batches.
	SplitType?: "None" | "TFRecord" | "Line" | "RecordIO"
}

#TransformJobDefinition: {
	// A string that determines the number of records included in a single mini-batch.
	BatchStrategy?: "MultiRecord" | "SingleRecord"
	Environment?: #Environment
	// The maximum number of parallel requests that can be sent to each instance in a transform job. The default value is 1.
	MaxConcurrentTransforms?: int & >=0
	// The maximum payload size allowed, in MB. A payload is the data portion of a record (without metadata).
	MaxPayloadInMB?: int & >=0
	TransformInput: #TransformInput
	TransformOutput: #TransformOutput
	TransformResources: #TransformResources
}

#TransformOutput: {
	// The MIME type used to specify the output data. Amazon SageMaker uses the MIME type with each http call to transfer data from the transform job.
	Accept?: string & =~".*" & strings.MaxRunes(256)
	// Defines how to assemble the results of the transform job as a single S3 object.
	AssembleWith?: "None" | "Line"
	// The AWS Key Management Service (AWS KMS) key that Amazon SageMaker uses to encrypt the model artifacts at rest using Amazon S3 server-side encryption.
	KmsKeyId?: string & =~".*" & strings.MaxRunes(2048)
	// The Amazon S3 path where you want Amazon SageMaker to store the results of the transform job.
	S3OutputPath: string & =~"^(https|s3)://([^/]+)/?(.*)$" & strings.MaxRunes(1024)
}

#TransformResources: {
	// The number of ML compute instances to use in the transform job. For distributed transform jobs, specify a value greater than 1. The default value is 1.
	InstanceCount: int & >=1
	// The ML compute instance type for the transform job.
	InstanceType: string
	// The AWS Key Management Service (AWS KMS) key that Amazon SageMaker uses to encrypt model data on the storage volume attached to the ML compute instance(s) that run the batch transform job.
	VolumeKmsKeyId?: string & =~".*" & strings.MaxRunes(2048)
}

#ValidationProfile: {
	// The name of the profile for the model package.
	ProfileName: string & =~"^[a-zA-Z0-9](-*[a-zA-Z0-9]){0,62}$" & strings.MinRunes(1) & strings.MaxRunes(63)
	TransformJobDefinition: #TransformJobDefinition
}

#ValidationSpecification: {
	ValidationProfiles: [...#ValidationProfile]
	// The IAM roles to be used for the validation of the model package.
	ValidationRole: string & =~"^arn:aws[a-z\\-]*:iam::\\d{12}:role/?[a-zA-Z_0-9+=,.@\\-_/]+$" & strings.MinRunes(20) & strings.MaxRunes(2048)
}
