package custompermissions

import "strings"

#Properties: {
	AwsAccountId: string & =~"^[0-9]{12}$" & strings.MinRunes(12) & strings.MaxRunes(12)
	Capabilities?: #Capabilities
	CustomPermissionsName: string & =~"^[a-zA-Z0-9+=,.@_-]+$" & strings.MinRunes(1) & strings.MaxRunes(64)
	Tags?: [...#Tag]
}

#Capabilities: {
	AccessAppsNativeDataStore?: #CapabilityState
	Action?: #CapabilityState
	AddOrRunAnomalyDetectionForAnalyses?: #CapabilityState
	AmazonBedrockARSAction?: #CapabilityState
	AmazonBedrockFSAction?: #CapabilityState
	AmazonBedrockKRSAction?: #CapabilityState
	AmazonSThreeAction?: #CapabilityState
	Analysis?: #CapabilityState
	ApproveFlowShareRequests?: #CapabilityState
	Apps?: #CapabilityState
	AsanaAction?: #CapabilityState
	Automate?: #CapabilityState
	BambooHRAction?: #CapabilityState
	BoxAgentAction?: #CapabilityState
	BuildCalculatedFieldWithQ?: #CapabilityState
	CanvaAgentAction?: #CapabilityState
	ChatAgent?: #CapabilityState
	ComprehendAction?: #CapabilityState
	ComprehendMedicalAction?: #CapabilityState
	ConfluenceAction?: #CapabilityState
	CreateAndUpdateAmazonBedrockARSAction?: #CapabilityState
	CreateAndUpdateAmazonBedrockFSAction?: #CapabilityState
	CreateAndUpdateAmazonBedrockKRSAction?: #CapabilityState
	CreateAndUpdateAmazonSThreeAction?: #CapabilityState
	CreateAndUpdateApps?: #CapabilityState
	CreateAndUpdateAsanaAction?: #CapabilityState
	CreateAndUpdateBambooHRAction?: #CapabilityState
	CreateAndUpdateBoxAgentAction?: #CapabilityState
	CreateAndUpdateCanvaAgentAction?: #CapabilityState
	CreateAndUpdateComprehendAction?: #CapabilityState
	CreateAndUpdateComprehendMedicalAction?: #CapabilityState
	CreateAndUpdateConfluenceAction?: #CapabilityState
	CreateAndUpdateDashboardEmailReports?: #CapabilityState
	CreateAndUpdateDataSources?: #CapabilityState
	CreateAndUpdateDatasets?: #CapabilityState
	CreateAndUpdateFactSetAction?: #CapabilityState
	CreateAndUpdateGenericHTTPAction?: #CapabilityState
	CreateAndUpdateGithubAction?: #CapabilityState
	CreateAndUpdateGoogleCalendarAction?: #CapabilityState
	CreateAndUpdateHubspotAction?: #CapabilityState
	CreateAndUpdateHuggingFaceAction?: #CapabilityState
	CreateAndUpdateIntercomAction?: #CapabilityState
	CreateAndUpdateJiraAction?: #CapabilityState
	CreateAndUpdateKnowledgeBases?: #CapabilityState
	CreateAndUpdateLinearAction?: #CapabilityState
	CreateAndUpdateMCPAction?: #CapabilityState
	CreateAndUpdateMSExchangeAction?: #CapabilityState
	CreateAndUpdateMSTeamsAction?: #CapabilityState
	CreateAndUpdateMondayAction?: #CapabilityState
	CreateAndUpdateNewRelicAction?: #CapabilityState
	CreateAndUpdateNotionAction?: #CapabilityState
	CreateAndUpdateOneDriveAction?: #CapabilityState
	CreateAndUpdateOpenAPIAction?: #CapabilityState
	CreateAndUpdatePagerDutyAction?: #CapabilityState
	CreateAndUpdateSAPBillOfMaterialAction?: #CapabilityState
	CreateAndUpdateSAPBusinessPartnerAction?: #CapabilityState
	CreateAndUpdateSAPMaterialStockAction?: #CapabilityState
	CreateAndUpdateSAPPhysicalInventoryAction?: #CapabilityState
	CreateAndUpdateSAPProductMasterDataAction?: #CapabilityState
	CreateAndUpdateSalesforceAction?: #CapabilityState
	CreateAndUpdateSandPGMIAction?: #CapabilityState
	CreateAndUpdateSandPGlobalEnergyAction?: #CapabilityState
	CreateAndUpdateServiceNowAction?: #CapabilityState
	CreateAndUpdateSharePointAction?: #CapabilityState
	CreateAndUpdateSlackAction?: #CapabilityState
	CreateAndUpdateSmartsheetAction?: #CapabilityState
	CreateAndUpdateTextractAction?: #CapabilityState
	CreateAndUpdateThemes?: #CapabilityState
	CreateAndUpdateThresholdAlerts?: #CapabilityState
	CreateAndUpdateZendeskAction?: #CapabilityState
	CreateChatAgents?: #CapabilityState
	CreateDashboardExecutiveSummaryWithQ?: #CapabilityState
	CreateSPICEDataset?: #CapabilityState
	CreateSharedFolders?: #CapabilityState
	CreateSpaces?: #CapabilityState
	Dashboard?: #CapabilityState
	EditVisualWithQ?: #CapabilityState
	ExportToCsv?: #CapabilityState
	ExportToCsvInScheduledReports?: #CapabilityState
	ExportToExcel?: #CapabilityState
	ExportToExcelInScheduledReports?: #CapabilityState
	ExportToPdf?: #CapabilityState
	ExportToPdfInScheduledReports?: #CapabilityState
	Extension?: #CapabilityState
	FactSetAction?: #CapabilityState
	Flow?: #CapabilityState
	GenericHTTPAction?: #CapabilityState
	GithubAction?: #CapabilityState
	GoogleCalendarAction?: #CapabilityState
	HubspotAction?: #CapabilityState
	HuggingFaceAction?: #CapabilityState
	IncludeContentInScheduledReportsEmail?: #CapabilityState
	IntercomAction?: #CapabilityState
	InvokeAppsAIInference?: #CapabilityState
	JiraAction?: #CapabilityState
	KnowledgeBase?: #CapabilityState
	LinearAction?: #CapabilityState
	MCPAction?: #CapabilityState
	MSExchangeAction?: #CapabilityState
	MSTeamsAction?: #CapabilityState
	ManageSharedFolders?: #CapabilityState
	MondayAction?: #CapabilityState
	NewRelicAction?: #CapabilityState
	NotionAction?: #CapabilityState
	OneDriveAction?: #CapabilityState
	OpenAPIAction?: #CapabilityState
	PagerDutyAction?: #CapabilityState
	PerformFlowUiTask?: #CapabilityState
	PrintReports?: #CapabilityState
	PublishWithoutApproval?: #CapabilityState
	RenameSharedFolders?: #CapabilityState
	Research?: #CapabilityState
	SAPBillOfMaterialAction?: #CapabilityState
	SAPBusinessPartnerAction?: #CapabilityState
	SAPMaterialStockAction?: #CapabilityState
	SAPPhysicalInventoryAction?: #CapabilityState
	SAPProductMasterDataAction?: #CapabilityState
	SalesforceAction?: #CapabilityState
	SandPGMIAction?: #CapabilityState
	SandPGlobalEnergyAction?: #CapabilityState
	ServiceNowAction?: #CapabilityState
	ShareAmazonBedrockARSAction?: #CapabilityState
	ShareAmazonBedrockFSAction?: #CapabilityState
	ShareAmazonBedrockKRSAction?: #CapabilityState
	ShareAmazonSThreeAction?: #CapabilityState
	ShareAnalyses?: #CapabilityState
	ShareApps?: #CapabilityState
	ShareAsanaAction?: #CapabilityState
	ShareBambooHRAction?: #CapabilityState
	ShareBoxAgentAction?: #CapabilityState
	ShareCanvaAgentAction?: #CapabilityState
	ShareChatAgents?: #CapabilityState
	ShareComprehendAction?: #CapabilityState
	ShareComprehendMedicalAction?: #CapabilityState
	ShareConfluenceAction?: #CapabilityState
	ShareDashboards?: #CapabilityState
	ShareDataSources?: #CapabilityState
	ShareDatasets?: #CapabilityState
	ShareFactSetAction?: #CapabilityState
	ShareGenericHTTPAction?: #CapabilityState
	ShareGithubAction?: #CapabilityState
	ShareGoogleCalendarAction?: #CapabilityState
	ShareHubspotAction?: #CapabilityState
	ShareHuggingFaceAction?: #CapabilityState
	ShareIntercomAction?: #CapabilityState
	ShareJiraAction?: #CapabilityState
	ShareKnowledgeBases?: #CapabilityState
	ShareLinearAction?: #CapabilityState
	ShareMCPAction?: #CapabilityState
	ShareMSExchangeAction?: #CapabilityState
	ShareMSTeamsAction?: #CapabilityState
	ShareMondayAction?: #CapabilityState
	ShareNewRelicAction?: #CapabilityState
	ShareNotionAction?: #CapabilityState
	ShareOneDriveAction?: #CapabilityState
	ShareOpenAPIAction?: #CapabilityState
	SharePagerDutyAction?: #CapabilityState
	SharePointAction?: #CapabilityState
	ShareSAPBillOfMaterialAction?: #CapabilityState
	ShareSAPBusinessPartnerAction?: #CapabilityState
	ShareSAPMaterialStockAction?: #CapabilityState
	ShareSAPPhysicalInventoryAction?: #CapabilityState
	ShareSAPProductMasterDataAction?: #CapabilityState
	ShareSalesforceAction?: #CapabilityState
	ShareSandPGMIAction?: #CapabilityState
	ShareSandPGlobalEnergyAction?: #CapabilityState
	ShareServiceNowAction?: #CapabilityState
	ShareSharePointAction?: #CapabilityState
	ShareSlackAction?: #CapabilityState
	ShareSmartsheetAction?: #CapabilityState
	ShareSpaces?: #CapabilityState
	ShareTextractAction?: #CapabilityState
	ShareZendeskAction?: #CapabilityState
	SlackAction?: #CapabilityState
	SmartsheetAction?: #CapabilityState
	Space?: #CapabilityState
	SubscribeDashboardEmailReports?: #CapabilityState
	TextractAction?: #CapabilityState
	Topic?: #CapabilityState
	UseAgentWebSearch?: #CapabilityState
	UseAmazonBedrockARSAction?: #CapabilityState
	UseAmazonBedrockFSAction?: #CapabilityState
	UseAmazonBedrockKRSAction?: #CapabilityState
	UseAmazonSThreeAction?: #CapabilityState
	UseAsanaAction?: #CapabilityState
	UseBambooHRAction?: #CapabilityState
	UseBedrockModels?: #CapabilityState
	UseBoxAgentAction?: #CapabilityState
	UseCanvaAgentAction?: #CapabilityState
	UseComprehendAction?: #CapabilityState
	UseComprehendMedicalAction?: #CapabilityState
	UseConfluenceAction?: #CapabilityState
	UseFactSetAction?: #CapabilityState
	UseGenericHTTPAction?: #CapabilityState
	UseGithubAction?: #CapabilityState
	UseGoogleCalendarAction?: #CapabilityState
	UseHubspotAction?: #CapabilityState
	UseHuggingFaceAction?: #CapabilityState
	UseIntercomAction?: #CapabilityState
	UseJiraAction?: #CapabilityState
	UseLinearAction?: #CapabilityState
	UseMCPAction?: #CapabilityState
	UseMSExchangeAction?: #CapabilityState
	UseMSTeamsAction?: #CapabilityState
	UseMondayAction?: #CapabilityState
	UseNewRelicAction?: #CapabilityState
	UseNotionAction?: #CapabilityState
	UseOneDriveAction?: #CapabilityState
	UseOpenAPIAction?: #CapabilityState
	UsePagerDutyAction?: #CapabilityState
	UseSAPBillOfMaterialAction?: #CapabilityState
	UseSAPBusinessPartnerAction?: #CapabilityState
	UseSAPMaterialStockAction?: #CapabilityState
	UseSAPPhysicalInventoryAction?: #CapabilityState
	UseSAPProductMasterDataAction?: #CapabilityState
	UseSalesforceAction?: #CapabilityState
	UseSandPGMIAction?: #CapabilityState
	UseSandPGlobalEnergyAction?: #CapabilityState
	UseServiceNowAction?: #CapabilityState
	UseSharePointAction?: #CapabilityState
	UseSlackAction?: #CapabilityState
	UseSmartsheetAction?: #CapabilityState
	UseTextractAction?: #CapabilityState
	UseZendeskAction?: #CapabilityState
	ViewAccountSPICECapacity?: #CapabilityState
	ZendeskAction?: #CapabilityState
}

#CapabilityState: "DENY"

#Tag: {
	// <p>Tag key.</p>
	Key: string & strings.MinRunes(1) & strings.MaxRunes(128)
	// <p>Tag value.</p>
	Value: string & strings.MinRunes(1) & strings.MaxRunes(256)
}
