package moduleversion

// #Attributes defines the read-only attributes returned by this resource.
// These are the values available via Fn::GetAtt.
//
// Usage:
//   fn.#GetAtt & {_logicalName: "MyResource", _attribute: "<attribute name>"}
#Attributes: {
	// The Amazon Resource Name (ARN) of the module.
	Arn: string & =~"^arn:aws[A-Za-z0-9-]{0,64}:cloudformation:[A-Za-z0-9-]{1,64}:([0-9]{12})?:type/module/.+$"
	// The description of the registered module.
	Description: string & strings.MinRunes(1) & strings.MaxRunes(1024)
	// The URL of a page providing detailed documentation for this module.
	DocumentationUrl: string & strings.MaxRunes(4096)
	// Indicator of whether this module version is the current default version
	IsDefaultVersion: bool
	// The schema defining input parameters to and resources generated by the module.
	Schema: string & strings.MinRunes(1) & strings.MaxRunes(16777216)
	// The time that the specified module version was registered.
	TimeCreated: string
	// The version ID of the module represented by this module instance.
	VersionId: string & =~"^[0-9]{8}$"
	// The scope at which the type is visible and usable in CloudFormation operations.
	// The only allowed value at present is:
	// PRIVATE: The type is only visible and usable within the account in which it is registered. Currently, AWS CloudFormation marks any types you register as PRIVATE.
	Visibility: "PRIVATE"
}
