package eventsubscription

#Properties: {
	// Indicates whether to activate the subscription. If you don't specify this property, CloudFormation activates the subscription.
	Enabled?: bool
	// A list of event categories for a source type that you want to subscribe to. If you don't specify this property, you are notified about all event categories.
	EventCategories?: [...string]
	// The Amazon Resource Name (ARN) of the Amazon SNS topic created for event notification. The ARN is created by Amazon SNS when you create a topic and subscribe to it.
	SnsTopicArn: string
	// A list of identifiers for which AWS DMS provides notification events.
	// If you don't specify a value, notifications are provided for all sources.
	// If you specify multiple values, they must be of the same type. For example, if you specify a database instance ID, then all of the other values must be database instance IDs.
	SourceIds?: [...string]
	// The type of AWS DMS resource that generates the events. For example, if you want to be notified of events generated by a replication instance, you set this parameter to replication-instance. If this value isn't specified, all events are returned.
	SourceType?: string
	// The name of the AWS DMS event notification subscription. This name must be less than 255 characters.
	SubscriptionName?: string
	// One or more tags to be assigned to the event subscription.
	Tags?: [...#Tag]
}

#Tag: {
	Key: string
	Value: string
}
