package functionconfiguration

// #Attributes defines the read-only attributes returned by this resource.
// These are the values available via Fn::GetAtt.
//
// Usage:
//   fn.#GetAtt & {_logicalName: "MyResource", _attribute: "<attribute name>"}
#Attributes: {
	// The ARN for the function generated by the service
	FunctionArn: string
	// The unique identifier for the function generated by the service
	FunctionId: string
}
