package multiregioncluster

// #Attributes defines the read-only attributes returned by this resource.
// These are the values available via Fn::GetAtt.
//
// Usage:
//   fn.#GetAtt & {_logicalName: "MyResource", _attribute: "<attribute name>"}
#Attributes: {
	// The name of the Global Datastore, it is generated by MemoryDB adding a prefix to MultiRegionClusterNameSuffix.
	MultiRegionClusterName: string
	// The status of the multi region cluster. For example, Available, Updating, Creating.
	Status: string
	// The Amazon Resource Name (ARN) of the multi region cluster.
	ARN: string
}
