package cluster

import "strings"

#Properties: {
	// The name of the Access Control List to associate with the cluster.
	ACLName: string & =~"[a-zA-Z][a-zA-Z0-9\\-]*"
	// A flag that enables automatic minor version upgrade when set to true.

You cannot modify the value of AutoMinorVersionUpgrade after the cluster is created. To enable AutoMinorVersionUpgrade on a cluster you must set AutoMinorVersionUpgrade to true when you create a cluster.
	AutoMinorVersionUpgrade?: bool
	// The name of the cluster. This value must be unique as it also serves as the cluster identifier.
	ClusterName: string & =~"[a-z][a-z0-9\\-]*"
	// Enables data tiering. Data tiering is only supported for clusters using the r6gd node type. This parameter must be set when using r6gd nodes.
	DataTiering?: #DataTieringStatus
	// An optional description of the cluster.
	Description?: string
	// The engine type used by the cluster.
	Engine?: string
	// The Redis engine version used by the cluster.
	EngineVersion?: string
	// The user-supplied name of a final cluster snapshot. This is the unique name that identifies the snapshot. MemoryDB creates the snapshot, and then deletes the cluster immediately afterward.
	FinalSnapshotName?: string
	// For clusters wth dual stack NetworkType, IpDiscovery controls the Ip protocol (ipv4 or ipv6) returned by the engine commands such as `cluster info` and `cluster nodes` which are used by clients to connect to the nodes in the cluster.
	IpDiscovery?: #SupportedIpDiscoveryTypes
	// The ID of the KMS key used to encrypt the cluster.
	KmsKeyId?: string
	// Specifies the weekly time range during which maintenance on the cluster is performed. It is specified as a range in the format ddd:hh24:mi-ddd:hh24:mi (24H Clock UTC). The minimum maintenance window is a 60 minute period.
	MaintenanceWindow?: string
	// The name of the Global Datastore, it is generated by MemoryDB adding a prefix to MultiRegionClusterNameSuffix.
	MultiRegionClusterName?: string
	// Must be either ipv4 | ipv6 | dual_stack.
	NetworkType?: #SupportedNetworkTypes
	// The compute and memory capacity of the nodes in the cluster.
	NodeType: string
	// The number of replicas to apply to each shard. The limit is 5.
	NumReplicasPerShard?: int
	// The number of shards the cluster will contain.
	NumShards?: int
	// The name of the parameter group associated with the cluster.
	ParameterGroupName?: string
	// The port number on which each member of the cluster accepts connections.
	Port?: int
	// One or more Amazon VPC security groups associated with this cluster.
	SecurityGroupIds?: [...string]
	// A list of Amazon Resource Names (ARN) that uniquely identify the RDB snapshot files stored in Amazon S3. The snapshot files are used to populate the new cluster. The Amazon S3 object name in the ARN cannot contain any commas.
	SnapshotArns?: [...string]
	// The name of a snapshot from which to restore data into the new cluster. The snapshot status changes to restoring while the new cluster is being created.
	SnapshotName?: string
	// The number of days for which MemoryDB retains automatic snapshots before deleting them. For example, if you set SnapshotRetentionLimit to 5, a snapshot that was taken today is retained for 5 days before being deleted.
	SnapshotRetentionLimit?: int
	// The daily time range (in UTC) during which MemoryDB begins taking a daily snapshot of your cluster.
	SnapshotWindow?: string
	// The Amazon Resource Name (ARN) of the Amazon Simple Notification Service (SNS) topic to which notifications are sent.
	SnsTopicArn?: string
	// The status of the Amazon SNS notification topic. Notifications are sent only if the status is enabled.
	SnsTopicStatus?: string
	// The name of the subnet group to be used for the cluster.
	SubnetGroupName?: string
	// A flag that enables in-transit encryption when set to true.

You cannot modify the value of TransitEncryptionEnabled after the cluster is created. To enable in-transit encryption on a cluster you must set TransitEncryptionEnabled to true when you create a cluster.
	TLSEnabled?: bool
	// An array of key-value pairs to apply to this cluster.
	Tags?: [...#Tag]
}

#Endpoint: {
	// The DNS address of the primary read-write node.
	Address?: string
	// The port number that the engine is listening on. 
	Port?: int
}

#Tag: {
	// The key for the tag. May not be null.
	Key: string & =~"^(?!aws:)(?!memorydb:)[a-zA-Z0-9 _\\.\\/=+:\\-@]{1,128}$" & strings.MinRunes(1) & strings.MaxRunes(128)
	// The tag's value. May be null.
	Value: string & =~"^(?!aws:)(?!memorydb:)[a-zA-Z0-9 _\\.\\/=+:\\-@]{1,256}$" & strings.MinRunes(1) & strings.MaxRunes(256)
}
