package api

// #Attributes defines the read-only attributes returned by this resource.
// These are the values available via Fn::GetAtt.
//
// Usage:
//   fn.#GetAtt & {_logicalName: "MyResource", _attribute: "<attribute name>"}
#Attributes: {
	// The unique identifier for the AppSync Api generated by the service
	ApiId: string
	Dns: #DnsMap
	// The Amazon Resource Name (ARN) of the AppSync Api
	ApiArn: string
}
