package trialcomponent

import "strings"

#Properties: {
	// The name of the component as displayed. If DisplayName isn't specified, TrialComponentName is displayed.
	DisplayName?: string & =~"^[a-zA-Z0-9](-*[a-zA-Z0-9]){0,119}$" & strings.MinRunes(1) & strings.MaxRunes(120)
	// The input artifacts for the component.
	InputArtifacts?: {...}
	MetadataProperties?: #MetadataProperties
	// The output artifacts for the component.
	OutputArtifacts?: {...}
	// The hyperparameters for the component.
	Parameters?: {...}
	Status?: #TrialComponentStatus
	// A list of tags to associate with the trial component.
	Tags?: [...{
		Key: string & =~"^([\\p{L}\\p{Z}\\p{N}_.:/=+\\-@]*)$" & strings.MinRunes(1) & strings.MaxRunes(128)
		Value: string & =~"^([\\p{L}\\p{Z}\\p{N}_.:/=+\\-@]*)$" & strings.MinRunes(0) & strings.MaxRunes(256)
	}]
	// The name of the trial component. Must be unique in your AWS account and is not case-sensitive.
	TrialComponentName: string & =~"^[a-zA-Z0-9](-*[a-zA-Z0-9]){0,119}$" & strings.MinRunes(1) & strings.MaxRunes(120)
}

#MetadataProperties: {
	// The commit ID.
	CommitId?: string & strings.MaxRunes(1024)
	// The entity this entity was generated by.
	GeneratedBy?: string & strings.MaxRunes(1024)
	// The project ID.
	ProjectId?: string & strings.MaxRunes(1024)
	// The repository.
	Repository?: string & strings.MaxRunes(1024)
}

#TrialComponentArtifact: {
	// The media type of the artifact.
	MediaType?: string & =~"^[-\\w]+\\/[-\\w+]+$" & strings.MaxRunes(64)
	// The location of the artifact.
	Value: string & strings.MaxRunes(2048)
}

#TrialComponentParameterValue: {
	// The numeric value of a numeric hyperparameter.
	NumberValue?: number
	// The string value of a categorical hyperparameter.
	StringValue?: string & strings.MaxRunes(2500)
}

#TrialComponentStatus: {
	// If the component failed, a message describing why.
	Message?: string & strings.MaxRunes(1024)
	// The status of the trial component.
	PrimaryStatus?: "InProgress" | "Completed" | "Failed" | "Stopping" | "Stopped"
}
